### ISSUE TITLE
[question] Copy node + remove some nested nodes

### ISSUE THREAD

**Issue by bilak** [schibsted/jslt#129] opened 2020-04-16 18:52 UTC
Hello
I'm evaluating this library. I wanted to ask question on SO, but I didn't found tag jslt, so maybe it would be nice to create one ;)

when using following example:
```json
{
  "cash_point_closing": {
    "number": 83076172,
    "taxonomy_version": "18.80.63",
    "head": {
      "creation_date": "1982-05-11T17:22:04.126Z",
      "first_id": "magna ",
      "last_id": null,
      "company": {
        "name": "ea c",
        "address": {
          "street": "ipsum esse quis est sed",
          "postal_code": "U",
          "city": "velit",
          "country_code": "CAN"
        },
        "tax_number": "Lorem ea nulla ve",
        "location": {
          "name": "velit amet sit",
          "address": {
            "street": "lab",
            "postal_code": "aute sed",
            "city": "ullamco quis"
          },
          "cash_register": {
            "id": "labore",
            "brand": "consectetur voluptate in",
            "model": "Excepteur l",
            "serial_number": "ullam",
            "vat_definitions": [
              {
                "id": 4,
                "percentage": 5.87
              },
              {
                "id": 5882777325,
                "percentage": 40.4,
                "description": "pariatur"
              }
            ],
            "base_currency_code": "ALL",
            "software": {
              "brand": "in tempor"
            },
            "slaves": [
              {
                "slave_id": "sun",
                "serial_number": "est officia",
                "brand": "minim Lorem dolore",
                "model": "dol",
                "software": {
                  "brand": "aliqua"
                }
              },
              {
                "slave_id": "amet",
                "serial_number": "ut consequat",
                "brand": "non",
                "model": "non",
                "software": {
                  "brand": "mollit magna"
                },
                "custom_fields": {
                  "": "aute commodo non"
                }
              }
            ],
            "purchaser_agencies": [
              {
                "id": 16562205,
                "name": "esse dolor aliqua",
                "address": {
                  "street": "dol",
                  "postal_code": "mag",
                  "city": "consectetur"
                },
                "tax_number": "volup"
              },
              {
                "id": 60044035,
                "name": "dolor",
                "address": {
                  "street": "ut Excepteur nulla",
                  "postal_code": "esse sed f",
                  "city": "culpa"
                },
                "tax_number": "labore ",
                "vat_id_number": "NMa\\ ],gHQ[+3V"
              }
            ],
            "processing_flags": {
              "UmsatzsteuerNichtErmittelbar": true
            }
          },
          "vat_id_number": "CQ5l!<"
        }
      },
      "business_date": "1987-04-09"
    }
  }
}
```

How can I copy entire `.cash_point_closing.head.company.location` excluding `cash_point_closing.head.company.location.cash_register.slaves` and `cash_point_closing.head.company.location.cash_register.purchaser_agencies`?

I was thinking about something like this, but it doesn't work:

```javascript
{
  "store_number" : .cash_point_closing.number,
  "report_type" : "DFKA",
  "report_version": .cash_point_closing.taxonomy_version,
  "report_creation_date": .cash_point_closing.head.creation_date,
  "company": {
    "name": .cash_point_closing.head.company.name,
    "address": .cash_point_closing.head.company.address,
    "tax_number": .cash_point_closing.head.company.tax_number,
    "location": {
      "name": .cash_point_closing.head.company.location.name,
      * - cash_register.slaves , cash_register.purchaser_agencies : .
    }
  }
}
```

I'm  testing it on http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html

Thanks

**Comment by larsga** [comment] 2020-04-16 19:13
I don't actually have enough reputation to create that tag, but I'm hoping to accumulate it. :) Anyway, it's fine to ask here.

So, I guess in the transform you posted, everything works OK, except `.company.location`?

The problem is the matching doesn't work there, because you're not matching against the same structure as the input has. With the new pipe operator (currently in PR #109, in review), you can do it like this:

```
{
  "store_number" : .cash_point_closing.number,
  "report_type" : "DFKA",
  "report_version": .cash_point_closing.taxonomy_version,
  "report_creation_date": .cash_point_closing.head.creation_date,
  "company": {
    "name": .cash_point_closing.head.company.name,
    "address": .cash_point_closing.head.company.address,
    "tax_number": .cash_point_closing.head.company.tax_number,
    "location": 

     // the next line makes it so that this node is the context after the pipe
     .cash_point_closing.head.company.location. | {
       // now we can use the star, because the location object is the context
       "cash_register" : {
         // we can match in here, too
         * - slaves, purchaser_agencies : .
       },
       * : . 
    }
  }
}
```

What this does is it matches against the location node, but you rewrite the `cash_register` field to the value you specify, where you use another matcher to say "copy everything except these two fields", and finally for the outer matcher you just say "copy everything exactly except the fields I just specified".

Without the pipe operator you basically have to spell all the fields out, or use an object for expression and do things more explicitly with `if` and so on.

**Comment by bilak** [comment] 2020-04-16 19:21
Ah that's nice feature, do you have any schedule when it can be merged? I really want to try this library in our project.

**Comment by larsga** [comment] 2020-04-16 19:33
We might be able to merge it tomorrow, actually. If you're impatient you can just check out that branch locally and build it and try it right now. The only thing that's missing is the final review of the code. It should be correct and feature complete.

**Comment by larsga** [comment] 2020-04-26 12:08
The pipe operator has been merged now, so you can build from master and try it. I'm closing this issue now.

**Closed by larsga** 2020-04-26 12:08 UTC
Labels: support
