### ISSUE TITLE
Unable to access variable in for loop

### ISSUE THREAD

**Issue by fredriv** [schibsted/jslt#70] opened 2019-04-08 13:34 UTC
I'm trying to create a reverse lookup table based on another variable, but it fails with a "No such variable" error.

Example JSLT that I expected to return the string "dk":
```
let lookup = {
  "dk" : "Denmark",
  "se" : "Sweden"
}
let reverse = {for ($lookup) .value : .key}
get-key($reverse, "Denmark")
```

If I comment out the call to `optimizeLets` on line 123 of ExpressionImpl.java it works as expected.

**Comment by larsga** [comment] 2019-04-08 15:53
That's very clearly a bug. It looks like the problem is that it's not picking up the reference to the `lookup` variable when scanning for variables.

**Comment by larsga** [comment] 2019-04-08 16:02
Found it. The problem is in the preparatory phase we optimize away the `lookup` variable, because it's static, but since object comprehensions didn't implement optimization the object comprehension never does it's part, which is to insert the literal where the variable reference was. So you get a reference to a variable that no longer exists.

Fixed by the commit above.

**Closed by larsga** 2019-04-08 16:02 UTC
Labels: bug

**Comment by fredriv** [comment] 2019-04-08 16:17
Excellent! 👍

**Comment by fredriv** [comment] 2019-05-29 09:33
@larsga Any chance for a release with this fix? :-) We're hitting this in another case now, where we don't have a workaround currently.

**Comment by larsga** [comment] 2019-05-29 09:38
Sure! I'll try to get it done during the weekend. 

I may try to sneak in PR #72 and also implement issue #56.
