### ISSUE TITLE
Function number(String) can't parse "01"

### ISSUE THREAD

**Issue by jcomouth-de** [schibsted/jslt#112] opened 2020-02-19 09:42 UTC
A string that consists only numbers and has one or more leading zeros can't be parsed. 
Is there an alternative solution to this behaviour?

**Comment by larsga** [comment] 2020-02-19 09:50
That's really weird. I was going to ask you what you meant, but I checked now, and indeed:

```
number("1") => 1
number("10") => 10
number("01") => error
```

This is definitely a bug, and will be fixed.

**Comment by larsga** [comment] 2020-02-19 09:52
The cause of the problem is that we use Jackson to parse the numbers, and the JSON syntax does not allow leading zeroes in integers nor in decimals. So clearly we have to either strip off the zeroes or start doing the conversion ourselves.

**Comment by jcomouth-de** [comment] 2020-02-19 10:11
Thanks for your quick feedback and for confirming and categorizing as a bug. I will first use regex to separate the leading zeros.

**Comment by ecerulm** [comment] 2020-02-21 09:42
A leading 0 indicates octal number in C, Python and JavaScript. JSON as @larsga mentioned does not support octal numbers.

Is the idea just to fix `number("01")` or also `number(01)`. I mean JSLT doesn't accept leading zero is literal numbers either:

    [01,02]  // this is also an error

So do you plan  to allow literal `01`  in everywhere in JSLT and if so would the leading zero be interpreted as octal number or decimal? . I'm assuming the answer is just allow it for `number("01")` and always interpret it as decimal.

Note: Keep in mind for the tests that you can't just remove leading zeros as you can encounter  a minus sign before the leading zeros as well. Som make sure to include things like  `number("-01")` in the tests.

**Comment by catull** [comment] 2020-02-21 13:16
Also, do not turn "0" -> "".

**Comment by jcomouth-de** [comment] 2020-02-21 15:57
As you mentioned I would like to turn “01” into 01. You are right about the minus sign.

**Comment by larsga** [comment] 2020-02-24 08:39
There is a difference between the literal syntax for numbers and the syntax accepted by `number()`. The latter is meant to be used among other things to convert human input to actual numbers, so it makes sense for it to be more lenient than what we are in source code.

Python `int`, JavaScript `parseInt`, XPath `number`, PostgreSQL `CAST`, and so on, all turn `"001"` into `1`.

So the idea here is _only_ to make `number()` more lenient. Not to change the JSLT syntax itself.

The reason JSLT doesn't accept leading zeroes in numeric literals is that JSON doesn't. We could expand JSLT to become more lenient here, but I can't really see any point in doing so.

Negative numbers were already included in the tests. I added `"0"` now as well.

**Comment by catull** [comment] 2020-02-25 08:36
Considering this project is "JSON query and Language Transformation", limiting numbers to not have leading zeros is more than reasonable.

Leniency is not a concern, IMHO.

Once you open up to it, you have to add more leniency in various parts of the library, and support, too.

Leading zero - or blanks - are a formatting matter, when you want to display amounts to be line up the hundreds / thousands etc, for humans, in tabular way.

Consistency is the keyword, IMHO.

Java SE's `Integter#parse()` [1] / `Long#parseLong()` [2] do not accept leading blanks or zeros.
They both state: 

>  The characters in the string must all be decimal digits, except that the first character may be an ASCII minus sign '-' (\u002D') to indicate a negative value or an ASCII plus sign '+' ('\u002B') to indicate a positive value.


[1]  [JDK 11 SE java.lang.Integer#parseInt(String)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html#parseInt(java.lang.String))
[2]  [JDK 11 SE java.lang.Long#parseLong(String)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Long.html#parseLong(java.lang.String))

**Comment by larsga** [comment] 2020-02-25 08:43
>  limiting numbers to not have leading zeros is more than reasonable.

There's a difference between numbers in source code (where we don't allow leading zeroes) and when parsing strings to numbers (where we are going to allow zeroes).

I agree leniency can be a slippery slope, but in this case I think we're on the right side of the line.

> Leading zero - or blanks - are a formatting matter

Yes, and formatting can occur in incoming strings. So we accept the zeroes, although we don't support whitespace or anything like that.

Java's `Integer.parseInt` also supports leading zeroes.

**Comment by catull** [comment] 2020-02-25 09:14
Indeed, I checked that, that is why I changed my comment above.

**Comment by larsga** [comment] 2020-02-25 09:17
I know, I just wanted to record another case of language designers making the same decision (to allow leading zeroes in strings being parsed).

**Comment by larsga** [comment] 2020-03-05 09:53
Fixed by commit 159a05d

**Closed by larsga** 2020-03-05 09:53 UTC
Labels: bug
