### ISSUE TITLE
from-json throws exception depending on the "string" param

### ISSUE THREAD

**Issue by Falci** [schibsted/jslt#150] opened 2020-09-10 14:42 UTC
[from-json](https://github.com/schibsted/jslt/blob/master/functions.md#from-jsonstring-fallback---value) throws exception instead of returning the fallback.

Example:
```jslt
from-json("\p", "fail")
```

**Comment by larsga** [comment] 2020-09-10 14:51
Are you sure this is not the JSLT failing to parse, rather than a runtime error?

When I try that in the demo it fails to parse. If I write `"\\p"` it works as expected.

More detail?

**Comment by Falci** [comment] 2020-09-10 19:49
I expected that `from-json` would accept ANY string in the first param. If that string can't be converted to a json, it should return the second param.
If the string can't be converted because it's `"{\"partial\""` or `"\p"` is not important.

**Comment by larsga** [comment] 2020-09-10 19:56
I'm sorry, but I think you don't understand what I'm saying.

That string is read twice. First when the JSLT is parsed, then again when it's executed.

Go [here](http://www.garshol.priv.no/jslt-demo) and paste your example query, then try to run it. If you look into the traceback you find this line:

```
at com.schibsted.spt.data.jslt.Parser.compile(Parser.java:226)
```

In other words, this failed when parsing the JSLT code. The error is: `Unknown escape sequence: \p at <inline>:1:11`. You've written something that isn't valid JSLT. It's conceptually no different from writing:

```
from json("", "fail")
```

Note the space between `from` and `json`.

Now if you instead write:

```
from-json("\\p", "fail")
```

You'll get `"fail"`.

So the problem here is that `"\p"` isn't a valid JSON string because of the broken escape sequence. We can't turn it into JSON to give to the function, which never gets called at all.

Try this:

```
from-json(., "fail")
```

When you can turn `"\p"` into a string Jackson can parse into `JsonNode` the JSLT will work just fine.

**Comment by larsga** [comment] 2020-09-10 19:59
You can't process this with jq, either:

```
Larss-MacBook-Pro-2:Desktop larsga$ echo '"\p"' | jq .
parse error: Invalid escape at line 1, column 4
```

**Comment by Falci** [comment] 2020-09-10 20:17
> You can't parse "\p" with any JSON parser.

Sure. I don't expect to be able to parse it. But since it's not parseable, shouldn't `from-json` return the fallback?

**Comment by larsga** [comment] 2020-09-11 06:00
Please make an effort to understand.

What you wrote is not a valid JSLT transform. The JSLT transform doesn't parse. `from-json` is never called.

**Comment by larsga** [comment] 2020-10-04 09:38
Closing this, as it's not a bug.

**Closed by larsga** 2020-10-04 09:38 UTC
Labels: support
