### ISSUE TITLE
Is it possible to invoke a specific function with a variable as name.

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#34] opened 2018-10-19 10:57 UTC
I have an input is:
```
{
  "A" : 60,
  "B" : 2
}
```
and this Jslt currently doesnt work :cry: 
```
def AFunc(value)
   if ($value >=60 )
    1
   else if($value >= 40)
    2
   else if($value >=20)
    3
   else if($value >=0)
    4
   else
    0

def BFunc(value)
   if ($value >=34 )
    3
   else if($value >=0)
    4
   else
    0

{for(.) .key: .key+"Func"(.value)}
```

and expected an output :
```
{
  "A" : 1,
  "B" : 4
}
```

Is there a possible way I can get the expected result without jslt like the following one, because I could have 500 key value pair in the input json.
```
def AFunc(value)
   if ($value >=60 )
    1
   else if($value >= 40)
    2
   else if($value >=20)
    3
   else if($value >=0)
    4
   else
    0

def BFunc(value)
   if ($value >=34 )
    3
   else if($value >=0)
    4
   else
    0

{
 "A":AFunc(.A),
 "B":AFunc(.B)
}
```

**Comment by larsga** [comment] 2018-11-30 07:52
Something like this is very difficult to do in JSLT, because the internal model is that expressions can only produce JSON values.

However, as long as you don't have dozens of functions you can just do this:

```
{for(.) 
  .key: if (.key == "A") AFunc(.value)
           else if (.key == "B") BFunc(.value)
           else error("Unknown key: " + .key)
}
```

**Comment by larsga** [comment] 2020-08-17 08:02
Closing as duplicate of issue #120

**Closed by larsga** 2020-08-17 08:02 UTC
Labels: support
