### ISSUE TITLE
Float problem

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#23] opened 2018-09-12 13:44 UTC
I have input 
```
{
  "value" : 6.777176437128938e+306
}

```

JSLT 
```
def x(value)
 if ($value >= 7.0)
    2
 else if($value < 7.0)
    1
 else 
    0

{
  "value" : x(.value)
}
```

And then I get a result as below, which is not correct.
I'm not sure where is wrong here, please help !
```
{
  "value" : 2
}
```

**Comment by larsga** [comment] 2018-09-12 14:47
I think the problem is that probably that my comparison code is too naive about `BigDecimal` nodes in Jackson. I'll look into this. Thanks for reporting!

**Comment by larsga** [comment] 2018-09-12 14:50
Uh, hang on. This giant float is bigger than `7.0`, so that answer looks right to me. I don't see any bug here?

**Comment by ca7erina** [comment] 2018-09-12 15:30
That giant float (6.777176437128938e+306) is less than 7.0

**Comment by larsga** [comment] 2018-09-12 15:35
I don't understand. It's `e+306` so the number is clearly hugely bigger than 7.0, mathematically speaking.

Your function `x` returns `2` if `e+306 >= 7.0`, and it does return `2.0`, which is the correct result.

If you paste `6.777176437128938e+306 >= 7.0` into here: http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html it produces `true`. So ... it looks correct to me?

**Comment by ca7erina** [comment] 2018-09-12 15:42
Sorry, I made a mistake, it's a correct answer.
It's supposed to be "e-306", and the result from the app is correct. Thanks for reply :)

**Comment by larsga** [comment] 2018-09-12 15:46
No worries. Everyone makes mistakes. :)

I'll close this, then.

**Closed by larsga** 2018-09-12 15:46 UTC
Labels: bug
